### ISSUE TITLE
Java agent file name in Dockerfile not working with OTEL Operator

### ISSUE THREAD

**Issue by riveryc** [signalfx/splunk-otel-java#660]
As the operator has the agent file hard coded as:
https://github.com/open-telemetry/opentelemetry-operator/blob/main/pkg/instrumentation/javaagent.go#L69

I think the easiest way to adopt this would be changing the default file name to `javaagent.jar` if possible in
https://github.com/signalfx/splunk-otel-java/blob/main/Dockerfile#L3

So we can directly use your built image with the OTEL operator. 

Is there any hard rule we have to use existing name?

**Comment by mateuszrzeszutek** [comment]
@owais can you take a look at this?

**Comment by owais** [comment]
Splunk does not officially support the community operator but you can use it with a custom image derived from official Splunk image(s) or configure operator differently.

Splunk does have it's own operator for Splunk OpenTelemetry Collector which supports Java auto-instrumentation. It is in beta though. github.com/signalfx/splunk-otel-operator

**Comment by riveryc** [comment]
Thanks for the sharing @owais . 

Could you please introduce the major difference between opensource version otel operator vs splunk otel operator?
As a Splunk customer, we'd like to leverage the best practise from vendor, however we don't want to be too far away from the open source project, what would be your recommendation?

**Comment by owais** [comment]
Biggest difference is that Splunk Operator deploys Splunk's distributions of agents (Collector, Java instrumentation, etc) with default configuration that makes more sense for Splunk customers. 

Another major difference is the CRDs supported by the operators. Community operator lets people deploy a general purpose otel deployment which can work with any vendor but with considerable effort on behalf of the user (configuration, etc). Splunk operator CRDs are optimized to simplify deployment for Splunk customers as much as possible. For example, basic CRD from community operator looks like the following where YOU have to configure everything by hand.

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```

While as Splunk operator CRD looks like the following:

```yaml
apiVersion: otel.splunk.com/v1alpha1
kind: Agent
metadata:
  name: splunk-otel
  namespace: splunk-otel-operator-system
spec:
  clusterName: <MY_CLUSTER_NAME>
  realm: <SPLUNK_REALM>
```

As you can see, Splunk operator knows how to configure the collector and instrumentation for Splunk customers and needs just the most important bits of info from you (realm, clustername and token). 

Hope this helps.
